burrow:
  host: localhost
  port: 8000

cluster:
#  include: *
#  exclude: : [cluster1, cluster2]

consumer_group:
#  include: *
  exclude: [burrow-local]
  metrics:
    - status
    - partition-lag
    - total-lag
    - max-lag
    - partition-current-offset
    - partition-max-offset
    - partition-status

topic:
#  include: *
  exclude: [__consumer_offsets, __confluent.support.metrics]
  metrics:
    - partition-offset


