burrow:
  host: localhost
  port: 8000

expose_port: 8001

cluster:
  include: '*'
#  exclude: : [cluster1, cluster2]

consumer_group:
  include: '*'
#  exclude: : ['group1', '*pattern*', 'prefix-*']
  metrics:
    - status
    - total-lag
    - max-lag
    - partition-lag
    - partition-offset
    - partition-status

topic:
  include: '*'
  exclude: '__consumer_offsets'
  metrics:
    - partition-offset


