burrow:
  host: localhost
  port: 8000

cluster:
  include: '*'
#  exclude: : [cluster1, cluster2]

consumer_group:
  include: ['test_group']
#  exclude: [burrow-local]
  metrics:
    - status
    - total-lag
    - max-lag
    - partition-lag
    - partition-offset
    - partition-status

topic:
  include: ['test','__consumer_offsets', '*confluent*']
  exclude: '*luent*'
  metrics:
    - partition-offset


